services:
  currency-publisher:
    build: .
    container_name: currency-publisher
    restart: unless-stopped
    environment:
      - RELAY_URL=ws://localhost:8080
      - NOSTR_PRIVATE_KEY=${NOSTR_PRIVATE_KEY}
    network_mode: host
